-- ============================================================================
-- SCRIPT COMPLET SUPABASE : CRÉATION DE LA TABLE 'profiles' & DÉCLENCHEUR (TRIGGER)
-- À exécuter dans l'éditeur SQL de votre tableau de bord Supabase (SQL Editor > New query > Run)
-- ============================================================================

-- 1. Création de la table publique 'profiles' liée à auth.users
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT,
  name TEXT,
  avatar_url TEXT,
  age INTEGER,
  bio TEXT,
  gender TEXT,
  city TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  photos TEXT[],
  interests TEXT[],
  details TEXT[],
  job TEXT,
  studies TEXT,
  alcohol TEXT,
  personality TEXT,
  zodiac TEXT,
  pets TEXT,
  key_question TEXT,
  is_verified BOOLEAN DEFAULT false,
  is_online BOOLEAN DEFAULT true,
  daily_likes_count INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (id)
);

-- Si la table existe déjà, ajout des colonnes :
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS daily_likes_count INTEGER DEFAULT 0;

-- 2. Activer la sécurité par niveau de ligne (Row Level Security - RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 3. Politiques de sécurité RLS
-- Public profile discovery is served through the authenticated API serializer;
-- the table itself keeps private columns visible only to the profile owner.
DROP POLICY IF EXISTS "Les profils sont visibles par tout le monde." ON public.profiles;
DROP POLICY IF EXISTS "Les utilisateurs peuvent voir leur propre profil." ON public.profiles;
CREATE POLICY "Les utilisateurs peuvent voir leur propre profil." ON public.profiles
  FOR SELECT TO authenticated USING (auth.uid() = id);

-- Permettre aux utilisateurs connectés de mettre à jour leur propre profil
DROP POLICY IF EXISTS "Les utilisateurs peuvent mettre à jour leur propre profil." ON public.profiles;
CREATE POLICY "Les utilisateurs peuvent mettre à jour leur propre profil." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Permettre aux utilisateurs d'insérer leur propre profil
DROP POLICY IF EXISTS "Les utilisateurs peuvent insérer leur propre profil." ON public.profiles;
CREATE POLICY "Les utilisateurs peuvent insérer leur propre profil." ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

-- Permettre aux utilisateurs de supprimer leur propre profil
DROP POLICY IF EXISTS "Les utilisateurs peuvent supprimer leur propre profil." ON public.profiles;
CREATE POLICY "Les utilisateurs peuvent supprimer leur propre profil." ON public.profiles
  FOR DELETE USING (auth.uid() = id);

-- 4. Fonction qui s'exécute automatiquement pour insérer le profil lors de l'inscription
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, username, name, updated_at)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    COALESCE(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    now()
  )
  ON CONFLICT (id) DO UPDATE SET
    username = EXCLUDED.username,
    name = EXCLUDED.name,
    updated_at = now();
  RETURN new;
END;
$$;

-- 5. Déclencheur (Trigger) qui appelle la fonction après chaque inscription dans auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 6. Tables complémentaires pour les fonctionnalités de rencontre (Optionnel mais recommandé)

-- 6.1 Table 'swipes' (Enregistre les swipes : qui a liké qui)
CREATE TABLE IF NOT EXISTS public.swipes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  liked_user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  is_liked BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Empêche de swiper plusieurs fois la même personne
  CONSTRAINT unique_swipe UNIQUE (user_id, liked_user_id)
);

-- Sécurité RLS pour swipes
ALTER TABLE public.swipes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Les utilisateurs peuvent insérer leurs propres swipes." ON public.swipes;
CREATE POLICY "Les utilisateurs peuvent insérer leurs propres swipes." ON public.swipes
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Les utilisateurs peuvent voir leurs propres swipes." ON public.swipes;
CREATE POLICY "Les utilisateurs peuvent voir leurs propres swipes." ON public.swipes
  FOR SELECT USING (auth.uid() = user_id OR auth.uid() = liked_user_id);

CREATE TABLE IF NOT EXISTS public.likes (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  target_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, target_id)
);

CREATE TABLE IF NOT EXISTS public.matches (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  profile_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, profile_id)
);

CREATE TABLE IF NOT EXISTS public.messages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  sender_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  receiver_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Les utilisateurs peuvent lire leurs likes." ON public.likes;
CREATE POLICY "Les utilisateurs peuvent lire leurs likes." ON public.likes
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR auth.uid() = target_id);
DROP POLICY IF EXISTS "Les utilisateurs peuvent enregistrer leurs likes." ON public.likes;
CREATE POLICY "Les utilisateurs peuvent enregistrer leurs likes." ON public.likes
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Les utilisateurs peuvent retirer leurs likes." ON public.likes;
CREATE POLICY "Les utilisateurs peuvent retirer leurs likes." ON public.likes
  FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Les participants peuvent lire leurs matchs." ON public.matches;
CREATE POLICY "Les participants peuvent lire leurs matchs." ON public.matches
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR auth.uid() = profile_id);

DROP POLICY IF EXISTS "Les participants peuvent lire leurs messages." ON public.messages;
CREATE POLICY "Les participants peuvent lire leurs messages." ON public.messages
  FOR SELECT TO authenticated
  USING (auth.uid() = sender_id OR auth.uid() = receiver_id);
DROP POLICY IF EXISTS "Les utilisateurs peuvent envoyer leurs messages." ON public.messages;
CREATE POLICY "Les utilisateurs peuvent envoyer leurs messages." ON public.messages
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = sender_id);
DROP POLICY IF EXISTS "Les expéditeurs peuvent supprimer leurs messages." ON public.messages;
CREATE POLICY "Les expéditeurs peuvent supprimer leurs messages." ON public.messages
  FOR DELETE TO authenticated
  USING (auth.uid() = sender_id);

-- ============================================================================
-- 7. PRIVATE PROFILE PHOTO STORAGE
-- ============================================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('profile-photos', 'profile-photos', false, 10485760, ARRAY['image/jpeg', 'image/png', 'image/webp'])
ON CONFLICT (id) DO UPDATE
SET public = false,
    file_size_limit = 10485760,
    allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp'];

DROP POLICY IF EXISTS "Les avatars sont visibles publiquement." ON storage.objects;
DROP POLICY IF EXISTS "Les utilisateurs peuvent uploader leur avatar." ON storage.objects;
DROP POLICY IF EXISTS "Les utilisateurs peuvent modifier ou remplacer leur avatar." ON storage.objects;
DROP POLICY IF EXISTS "profile photos are publicly readable" ON storage.objects;
DROP POLICY IF EXISTS "users read their own profile photos" ON storage.objects;
DROP POLICY IF EXISTS "users upload their own profile photos" ON storage.objects;
DROP POLICY IF EXISTS "users update their own profile photos" ON storage.objects;
DROP POLICY IF EXISTS "users delete their own profile photos" ON storage.objects;

CREATE POLICY "users read their own profile photos" ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'profile-photos' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "users upload their own profile photos" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'profile-photos' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "users update their own profile photos" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'profile-photos' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "users delete their own profile photos" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'profile-photos' AND (storage.foldername(name))[1] = auth.uid()::text);

UPDATE storage.buckets
SET public = false
WHERE id = 'avatars';

-- ============================================================================
-- 8. TÂCHES PLANIFIÉES ET AUTOMATISATIONS (EXTENSION pg_cron)
-- ============================================================================

-- 8.1 Activer pg_cron dans la base de données
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;

-- 8.2 Tâche 1 : Réinitialisation du compteur de likes à minuit pour tous les niveaux (Freemium, Extra, Premium)
SELECT cron.schedule(
  'reset-compteurs-tous-niveaux',
  '0 0 * * *', -- Chaque nuit à minuit pile
  $$ UPDATE public.profiles SET daily_likes_count = 0; $$
);

-- 8.3 Tâche 2 : Nettoyage automatique de l'historique des vieux swipes / rejetés (Sécurité anti-triche & allègement)
SELECT cron.schedule(
  'nettoyer-historique-swipes',
  '0 2 * * *', -- S'exécute toutes les nuits à 2h du matin
  $$ 
    DELETE FROM public.swipes 
    WHERE created_at < now() - interval '24 hours' 
      AND (is_match = false OR is_match IS NULL); 
  $$
);

-- 8.4 Tâche 3 : Purge des comptes non activés / e-mails non confirmés (+ de 7 jours)
SELECT cron.schedule(
  'nettoyage-comptes-non-actives',
  '0 3 * * *',
  $$ DELETE FROM auth.users WHERE email_confirmed_at IS NULL AND created_at < now() - interval '7 days'; $$
);

-- ============================================================================
-- 9. COMMANDES UTILES POUR SURVEILLER ET GÉRER VOS TÂCHES CRON
-- ============================================================================
-- Voir la liste des tâches actives :
-- SELECT * FROM cron.job;

-- Voir l'historique et le statut d'exécution des tâches :
-- SELECT * FROM cron.job_run_details ORDER BY start_time DESC LIMIT 10;

-- Désactiver ou supprimer une tâche planifiée :
-- SELECT cron.unschedule('reset-compteurs-tous-niveaux');
-- SELECT cron.unschedule('nettoyer-historique-swipes');
-- SELECT cron.unschedule('nettoyage-comptes-non-actives');
